### ISSUE TITLE
Using shader and scene datas as json

### ISSUE THREAD

**Issue by BlackGoku36** [armory3d/iron_examples#4]
I am trying to use shader and scene datas as JSON, as given from here ->https://github.com/armory3d/iron_examples/commit/549643a595b5133320a17f259f3e85819b01b3f9 .(Ik, that it removed because of it not working in latest iron's json format), i am trying to do same in here-> https://github.com/BlackGoku36/rasteringwithiron/blob/dev/Sources/Main.hx (note: it is in `Dev` branch, not `master` branch), thought it compiles correctly, object isn't initialized, or shown, i tried running it in renderdocs and it doesn't show anything in `Mesh Output`, am i missing something that need mesh to show up?
Any more information needed?

**Comment by luboslenco** [comment]
Linking to http://forums.armory3d.org/t/using-iron-with-seperate-scene-and-material-data-in-json-file/2502.
