### ISSUE TITLE
Geometry.hx fails with LockInt16 no longer exists

### ISSUE THREAD

**Issue by jrdoughty** [armory3d/iron_examples#6]
tried replacing it with:

		var vf = vertexBuffer.lock();
		vertices = new Int16Array(vf.byteLength);
		for(i in 0...vf.byteLength){vertices.setInt16(i,vf.getInt16(i));}

But I'm guessing converting Float32 to Int16 isn't quite so straight forward.

**Comment by jrdoughty** [comment]
I found its using an old version of iron. I manually copied the latest iron over and Triangle/Mesh rendered. Texture shows the blue background, but no luck seing the textured cube. json doesn't appear to want to run.

**Comment by jrdoughty** [comment]
https://github.com/armory3d/iron/issues/119 looks like this might fix it. I'll have to test it another time

**Comment by luboslenco** [comment]
Should no longer be an issue nowadays. Thanks for report.
